### ISSUE TITLE
BSPWM - Aesthetic Dotfiles 👌 Roadmap 2024

### ISSUE THREAD

**Issue by FQ211776** [FQ211776/dotfiles#3]
# BSPWM - Aesthetic Dotfiles 👌 Roadmap 2024

En este issue hago un cuadro general de todas las tareas que pretendo incluir en este repositorio, cuando lkega el momento y comienzo a trabajar en uno en especifico lo convierto en un issue, de esta forma tengo en un solo lugar una vista global des estado del repositorio.

Descripcion de las anotaciones:

| Mark          | Description      |
| ------------- | ---------------- |
| bullet        | No iniciado |
| check mark    | Completado   |
| :runner:      | En proceso    |
| :muscle:      | Casi terminado    |
| :red_circle:  | Bloqueado    |

### Values
Before we go into the details, let's start with our values that guide the development of VS Code. They have pretty much remained the same since the early days and we don't have any intention to change them:
- Out of the box, VS Code is a text editor: lightweight and fast. Users may install extensions that impact the appearance and nature of VS Code.
- Performance trumps functionality.
- Simple, uniform UI and UI interactions.
- Allow for CLI / UI co-existence and interplay whenever possible.
- Although we limit the UI choices extension authors can make, authors can write powerful extensions such as one that turn VS Code into an IDE with bells and whistles.

### Themes for 2023/24
Over the course of the last years we made significant progress on our original roadmap. So, not surprisingly one major topic for this year is to evolve this roadmap to guide us for the next 2-3 years. We will continue our push to become the leader in accessibility, and bring features to you that you're asking for. The elephant in the room is clearly the support for AI. We will continue to focus on exploring and understanding how AI changes how we all develop. Just like with Remote, parts of this work will be in the open, and parts will be closed source. We will continue to develop, improve, and ship the GitHub Copilot Chat extension.

---
# [TRIARQUÍA]

###  [Ranger](https://github.com/FQ211776/dotfiles/wiki/Ranger-%E2%80%90-Altamente-modificado)

Refs: 
- [ ] [ranger](https://github.com/FQ211776/dotfiles/issues/2) 
   - [ ] Crear rama y agregar dotfiles
   - [ ] Documentar el flujo de trabajo en la wiki
   - [ ] Documentar los atajos de teclado a keybindings.md
   - [ ] Agregar a seccion TREE en el README.md
   - [ ] Agregar capturas de pantalla en el README.md

Complexity: 2

## Tmux and Friends

---
# Archivos de configuracion incluidos

---
## Shells

---
## Shell Prompts

---
## Development Tools

---
## System Tools

---
## Terminal Emulators

---
## Browser

---
## Window Management

---
## Summary

These are examples of some of the work we will be focusing on in the next 12-18 months. We continuously tune the plan based on feedback and we will provide more detail in each of our [monthly iteration plans](https://github.com/Microsoft/vscode/wiki/Iteration-Plans). We will develop our next roadmap in around 12 months from now. Please follow along and let us know what you think!
